[tools]
node = "lts"
go = "latest"
rust = { version = "stable", components = "clippy,rustfmt,rust-analzyer" }
just = "latest"
uv = "latest"
jj = "latest"
eza = "latest"
glow = "latest"
delta = "latest"
fx = "latest"
neovim = "0.11.2"
tmux = "latest"
zoxide = "latest"
bat = "latest"
fd = "latest"
ripgrep = "latest"
jq = "latest"
pandoc = "latest"
"cargo:https://github.com/oyarsa/fleche" = "branch:master"
btop = "latest"
lua-language-server = "latest"
gh = "latest"
atuin = "latest"
vivid = "latest"
bat-extras = "latest"
codex = "latest"
fzf = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:llm" = "latest"
