[tools]
node = "lts"
go = "latest"
rust = { version = "stable", components = "clippy,rustfmt" }
just = "latest"
uv = "latest"
jj = "latest"
eza = "latest"
glow = "latest"
starship = "latest"
delta = "latest"
bob = "latest"
fx = "latest"
